name: Sync Docs Page Event Dispatch

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: ${{ secrets.REPO_NAME_DOCS }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: sync-docs-page-event
